const terminals = [
  {
    vendor: 'INPAS',
    model: 'PAX S920 Wi-FI',
    connection_type: 'WiFI(на наклейке с обратной стороны Obw)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX S920 Wi-FI+4G',
    connection_type:
      'SIM 2G, 3G,4G + WIFI (на наклейке с обратной стороны OPw)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX S920 3G',
    connection_type: 'SIM 2G, 3G (на наклейке с обратной стороны OwO)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX D230(Стационарный)',
    connection_type: 'Ethernet, WIFI, SIM 2G,3G,4G',
    terminal_type: 'стационарный',
    pinpad: 'S200',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'PAX D230(Мобильный)',
    connection_type: 'WIFI, SIM 2G,3G,4G',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX D270(Мобильный)',
    connection_type:
      'WIFI, SIM 2G,3G,4G (на наклейке с обратной стороны OAW)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX D270(Стационарный)',
    connection_type:
      'Ethernet, WIFI, SIM 2G,3G,4G (на наклейке с обратной стороны ODA)',
    terminal_type: 'стационарный',
    pinpad: 'S200',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'PAX S80',
    connection_type: 'Ethernet + Sim  2G',
    terminal_type: 'стационарный',
    pinpad: 'S200',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'PAX S800',
    connection_type: 'Ethernet + Sim  2G,3G',
    terminal_type: 'стационарный',
    pinpad: 'S200',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'PAX Q80S',
    connection_type: 'Ethernet + Sim  2G.3G',
    terminal_type: 'стационарный',
    pinpad: 'S200',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'PAX S300',
    connection_type: 'Ethernet + USB + COM',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да*',
    preauth: 'да',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX Q25',
    connection_type: 'Ethernet + USB + COM + WIFI',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да*',
    preauth: 'да',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone v240m 3G',
    connection_type: 'SIM 2G,3G',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone v240m WIFI',
    connection_type: 'WIFI',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone v200t',
    connection_type: 'Ethernet + SIM 2G, 3G',
    terminal_type: 'стационарный',
    pinpad: '1000SE',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Veifone c205c',
    connection_type: 'Ethernet',
    terminal_type: 'стационарный',
    pinpad: '1000SE',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone p400',
    connection_type: 'Ethernet + USB + COM',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да*',
    preauth: 'да',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone VX520',
    connection_type: 'Ethernet + SIM 2G, 3G',
    terminal_type: 'стационарный',
    pinpad: '1000SE',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone VX675 WIFI',
    connection_type: 'WIFI',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone VX675 3G',
    connection_type: 'SIM 2G,3G',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Castles Vega3000 E1',
    connection_type: 'SIM 2G,3G',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'нет',
    preauth: 'нет',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Castles Vega3000 E',
    connection_type: 'WIFI, SIM 2G',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'нет',
    preauth: 'нет',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Castles Vega3000 F',
    connection_type: 'Ethernet + SIM 2G, 3G',
    terminal_type: 'стационарный',
    pinpad: 'V3 UltraLite',
    sbp: 'нет',
    preauth: 'нет',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Castles Vega3000 D',
    connection_type: 'Ethernet',
    terminal_type: 'стационарный',
    pinpad: 'V3 UltraLite',
    sbp: 'нет',
    preauth: 'нет',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PayMob A90',
    connection_type: 'WiFI + SIM',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Aisino V71 SIM',
    connection_type: 'SIM 2G,3G,4G (определяется по маркировке)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Aisino V71 WIFI',
    connection_type: 'WIFI (определяется по маркировке)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Aisino V73 4G + WIFI',
    connection_type:
      'Маркировка на наклейке WIFI-BT-GPS, или GPS, Wifi+SIM(2G,3G,4G)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Aisino V80SE',
    connection_type: 'Ethernet + SIM 2G, 3G',
    terminal_type: 'стационарный',
    pinpad: 'V10',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'Aisino V80SE',
    connection_type: 'Ethernet + SIM 2G, 3G,4G',
    terminal_type: 'стационарный',
    pinpad: 'V10',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'Aisino V80SE (WIFI, SIM, ETH)',
    connection_type: 'Ethernet, WIFI, SIM 2G,3G,4G',
    terminal_type: 'стационарный',
    pinpad: 'V10',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'Aisino V37',
    connection_type: 'USB',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да*',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Centern K9(ПБФ-Free-касса / Unitode)',
    connection_type: 'WiFI + SIM',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'MoreFun MF960',
    connection_type: 'WiFI + SIM',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Teplo P8',
    connection_type: 'USB + WiFi + Ethernet',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да*',
    preauth: 'нет',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Tactilion H9 / Tactilion H9 Pro',
    connection_type: 'WiFI + SIM',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Tactilion H9 Pro',
    connection_type: 'Ethernet, WIFI, SIM',
    terminal_type: 'стационарный',
    pinpad: 'MP70',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'Tactilion G25',
    connection_type: 'WiFI + SIM',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'MF67',
    connection_type: 'USB',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да*',
    preauth: 'да',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
]
