const terminals = [
  {
    vendor: 'INPAS',
    model: 'PAX S920 (Wi-FI)',
    connection_type: 'WiFI(на наклейке с обратной стороны Obw)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX S920 (Wi-FI+4G)',
    connection_type:
      'SIM 2G, 3G,4G + WIFI (на наклейке с обратной стороны OPw)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX S920 (3G) (SIM)',
    connection_type: 'SIM 2G, 3G (на наклейке с обратной стороны OwO)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX D230 (Стационарный) (Eth, Wi-Fi, SIM)',
    connection_type: 'Ethernet, WIFI, SIM 2G,3G,4G',
    terminal_type: 'стационарный',
    pinpad: 'S200',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'PAX D230 (Мобильный) (Wi-Fi, SIM)',
    connection_type: 'WIFI, SIM 2G,3G,4G',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX D270 (Мобильный) (Wi-Fi, SIM)',
    connection_type:
      'WIFI, SIM 2G,3G,4G (на наклейке с обратной стороны OAW)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX D270(Стационарный) (Eth, Wi-Fi, SIM)',
    connection_type:
      'Ethernet, WIFI, SIM 2G,3G,4G (на наклейке с обратной стороны ODA)',
    terminal_type: 'стационарный',
    pinpad: 'S200',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'PAX S80 (Eth, SIM)',
    connection_type: 'Ethernet + Sim  2G',
    terminal_type: 'стационарный',
    pinpad: 'S200',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'PAX S800 (Eth, SIM)',
    connection_type: 'Ethernet + Sim  2G, 3G',
    terminal_type: 'стационарный',
    pinpad: 'S200',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'PAX Q80S (Eth, SIM)',
    connection_type: 'Ethernet + Sim  2G, 3G',
    terminal_type: 'стационарный',
    pinpad: 'S200',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'INPAS',
    model: 'PAX S300 (Eth, USB, COM)',
    connection_type: 'Ethernet + USB + COM',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'PAX Q25 (Eth, USB, COM, Wi-Fi)',
    connection_type: 'Ethernet + USB + COM + WIFI',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone v240m 3G (SIM)',
    connection_type: 'SIM 2G,3G',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone v240m WIFI',
    connection_type: 'WIFI',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone v200t (Eth, SIM)',
    connection_type: 'Ethernet + SIM 2G, 3G',
    terminal_type: 'стационарный',
    pinpad: '1000SE',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Veifone c205c (Eth)',
    connection_type: 'Ethernet',
    terminal_type: 'стационарный',
    pinpad: '1000SE',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone p400 (Eth, USB, COM)',
    connection_type: 'Ethernet + USB + COM',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone VX520 (Eth, SIM)',
    connection_type: 'Ethernet + SIM 2G, 3G',
    terminal_type: 'стационарный',
    pinpad: '1000SE',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone VX675 WIFI',
    connection_type: 'WIFI',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'INPAS',
    model: 'Verifone VX675 3G',
    connection_type: 'SIM 2G,3G',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'LANTER',
    model: 'Castles Vega3000 E1 (SIM)',
    connection_type: 'SIM 2G,3G',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'нет',
    preauth: 'нет',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'LANTER',
    model: 'Castles Vega3000 E (Wi-Fi, SIM)',
    connection_type: 'WIFI, SIM 2G',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'нет',
    preauth: 'нет',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'LANTER',
    model: 'Castles Vega3000 F (Eth, SIM)',
    connection_type: 'Ethernet + SIM 2G, 3G',
    terminal_type: 'стационарный',
    pinpad: 'V3 UltraLite',
    sbp: 'нет',
    preauth: 'нет',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'LANTER',
    model: 'Castles Vega3000 D (Eth)',
    connection_type: 'Ethernet',
    terminal_type: 'стационарный',
    pinpad: 'V3 UltraLite',
    sbp: 'нет',
    preauth: 'нет',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'LANTER',
    model: 'PayMob A90 (Wi-Fi, SIM)',
    connection_type: 'WiFI + SIM',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'PBF',
    model: 'Aisino V71 SIM',
    connection_type: 'SIM 2G,3G,4G (определяется по маркировке)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'PBF',
    model: 'Aisino V71 WIFI',
    connection_type: 'WIFI (определяется по маркировке)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'PBF',
    model: 'Aisino V73 (4G + WIFI)',
    connection_type:
      'Маркировка на наклейке WIFI-BT-GPS, или GPS, Wifi+SIM(2G,3G,4G)',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'PBF',
    model: 'Aisino V80SE (Eth, SIM)',
    connection_type: 'Ethernet + SIM 2G, 3G, 4G (4G -вариативно)',
    terminal_type: 'стационарный',
    pinpad: 'V10',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'PBF',
    model: 'Aisino V80SE (WIFI, SIM, ETH)',
    connection_type: 'Ethernet, WIFI, SIM 2G,3G,4G',
    terminal_type: 'стационарный',
    pinpad: 'V10',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'PBF',
    model: 'Aisino V37 (USB)',
    connection_type: 'USB',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'PBF',
    model: 'Centerm K9(ПБФ-Free-касса / Unitode) (Wi-Fi, SIM)',
    connection_type: 'WiFI + SIM',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'PBF',
    model: 'MoreFun MF960 (Wi-Fi, SIM)',
    connection_type: 'WiFI + SIM',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'PBF',
    model: 'Telpo P8 (Eth, Wi-Fi, USB)',
    connection_type: 'USB + WiFi + Ethernet',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'нет',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'Надеск',
    model: 'Tactilion H9 / Tactilion H9 Pro (Wi-Fi, SIM)',
    connection_type: 'WiFI + SIM',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'Надеск',
    model: 'Tactilion H9 Pro (Eth, Wi-Fi, SIM)',
    connection_type: 'Ethernet, WIFI, SIM',
    terminal_type: 'стационарный',
    pinpad: 'MP70',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'да',
  },
  {
    vendor: 'Надеск',
    model: 'Tactilion G25 (Wi-Fi, SIM)',
    connection_type: 'WiFI + SIM',
    terminal_type: 'мобильный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'да',
    qr_on_pinpad: 'нет',
  },
  {
    vendor: 'MoreFun',
    model: 'MF67 (USB)',
    connection_type: 'USB',
    terminal_type: 'интеграционный',
    pinpad: 'нет',
    sbp: 'да',
    preauth: 'да',
    no_cash: 'нет',
    qr_on_pinpad: 'нет',
  },
]
